<?php

/**
 * Implements hook_theme
 */
/*
function onesearch_theme($existing, $type, $theme, $path) {
  return [
    'onesearch'     => [
      'variables' => [
        // define defaults for any variables you want in the twig file
	'form' => \Drupal::formBuilder()->getForm('Drupal\onesearch\Form\OnesearchSearchForm'),
        'attributes' => [
           'class' => ['onesearch'],
         ], //etc
      ],
    ],
  ];
}
*/
