<?php

	/**
	 * Implements hook_theme
	 */
	function onesearch_theme($existing, $type, $theme, $path) {
		return [
			'onesearch_block' => [
			'render element' => 'form',
			'template' => 'onesearch',
			],
		];
	}

	/**
	* {@inheritdoc}
	*/
	function onesearch_preprocess_block(&$variables) {
		if ($variables['plugin_id'] == 'onesearch_search__block') {
			$variables['#attached']['library'][] = 'onesearch/onesearch';
		}
	}

