<?php

/**
 * @file
 * Main module file.
 */

use Drupal\Core\State;

/**
 * Implements hook_preprocess_node
 */
function emergency_alert_preprocess_node(&$variables) {
	\Drupal::state()->set('emergency','Test');
}

/**
 * Implements hook_preprocess_block
 */
function emergency_alert_preprocess_block(&$variables) {
	// Possible future enhancements to the block
	// will go here.
}

/**
* Implements hook_theme() to add the template definition. 
**/
function emergency_alert_theme($existing, $type, $theme, $path) {
	return array(
		'block__emergency_alert' => array(
			'render element' => 'elements',
			'template' => 'block--emergency-alert',
			'base_hook' => 'block',
			'variables' => array(
				'emergency' => \Drupal::state()->get('emergency')
			)
		)
	);
}
