<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
//use Drupal\Core\Entity;
//use Drupal\Core\Entity\EntityInterface;

//Implements hook_form_FORM_ID_alter()
function faculty_page_auto_title_faculty_page_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  //  $form['title']['#access'] = FALSE;

}


function faculty_page_auto_title_node_create(NodeInterface $node) {

  switch ($node->getType()) {
    case 'faculty_page':
      //Change the title
//	$node->setTitle('');      
	break;
  }
}

