<?php

/**
 * @file
 * Main module file for Miramar College.
 * Contains functions that alter Drupal setting and behaviors
 */





/**
 * Implements hook_preprocess_HOOK() for block templates.
 *
 * @todo This is just a poor man's implementation of changing svg logo to png.
 *
 * @see https://www.drupal.org/node/2472127#comment-10458517
 */

/**
 * Implements hook_preprocess_html()
 * 
 */

/*
function miramarcustom_preprocess_html(&$variables) {

Just a basic browser-level preprocess, for possible future use.

}*/

function miramarcustom_preprocess_page(&$variables) {

	// Set path to theme images

	$imagepath = base_path() . drupal_get_path('theme', 'miramar');

	\Drupal::configFactory()
		->getEditable('miramarcustom.settings')
		->set('image_path', $imagepath)
		->save();

	// Get client IP and determine if it's from on campus

	if (!empty($_SERVER["HTTP_CLIENT_IP"]))
	{
	 //check for ip from share internet
	 $theIP = $_SERVER["HTTP_CLIENT_IP"];
	}
	elseif (!empty($_SERVER["HTTP_X_FORWARDED_FOR"]))
	{
	 // Check for the Proxy User
	 $theIP = $_SERVER["HTTP_X_FORWARDED_FOR"];
	}
	else
	{
	 $theIP = $_SERVER["REMOTE_ADDR"];
	}

	if(substr($theIP,0,2) == '10') {
		\Drupal::configFactory()
			->getEditable('miramarcustom.settings')
			->set('local_ip', TRUE)
			->save();
	}
	else {
		\Drupal::configFactory()
			->getEditable('miramarcustom.settings')
			->set('local_ip', FALSE)
			->save();
	}

	\Drupal::configFactory()
		->getEditable('miramarcustom.settings')
		->set('client_ip', $theIP)
		->save();

	\Drupal::configFactory()
		->getEditable('miramarcustom.settings')
		->set('issues_link', '<a href="http://webissues.ics.sdmiramar.net/issue/report?url=' . $_SERVER['REQUEST_URI'] . '">Report Issues With This Page</a>')
		->save();

}

/**
 * Implements hook_preprocess_page()
 * Reformats event dates for display using correct time zone.
 */

function miramarcustom_preprocess_node(&$variables) {
	if(!empty($variables['node']))
	{
		$node = $variables['node'];

		switch($node->getType()) {
			case "event":
			case "committee_meeting":
				$realTimezone = new DateTimeZone('America/Los_Angeles');
				$gmtTimezone = new DateTimeZone('GMT');
				$localDateTime = new DateTime($node->field_event_date->value, $gmtTimezone);
				$offset = $realTimezone->getOffset($localDateTime);
				$localInterval = DateInterval::createFromDateString((string)$offset . 'seconds');
				$localDateTime->add($localInterval);
				$result = $localDateTime->format('l, F j');
				$variables['newdate'] = $result;
				break;
			case "sdccd_campaign":
			break;
		case "committee":
			$variables['ctype'] = "committee";
		break;
		case "program":
			$variables['ctype'] = "program";
			\Drupal::configFactory()
				->getEditable('miramarcustom.settings')
				->set('prog_call', '<div class="spacer" style="height:0.1em">&nbsp;</div><div class="call hide-xs"><a href="#course_seq"><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span>What to Take</a></div>')
				->save();
		break;
		case "custom_web_page":
			$variables['ctype'] = "page";
			\Drupal::configFactory()
				->getEditable('miramarcustom.settings')
				->set('prog_call', '')
				->save();
		break;
		default:
		}
	}
}

function miramarcustom_theme($existing, $type, $theme, $path) {
$arrLrcItems = array(
			0 => array
			(
				title => 'Catalog',
				url	=> 'http://libcat.sdccd.edu.libraryaccess.sdmiramar.edu:8080/ipac20/ipac.jsp?profile=mm'
			),
			1 => array
			(
				title => 'My Account',
				url	=> 'http://libcat.sdccd.edu.libraryaccess.sdmiramar.edu:8080/ipac20/ipac.jsp?session=L4527172H8614.52&profile=mm&menu=account&ts=1452717226201'
			),
			2 => array
			(
				title => 'Articles/Databases',
				url	=> '/campus/lrc/databases'
			),
			3 => array
			(
				title => 'Videos',
				url	=> 'http://libcat.sdccd.edu.libraryaccess.sdmiramar.edu:8080/hipres/sdccd/avsearch_miramar.html'
			),
			4 => array
			(
				title => 'Research Guides',
				url	=> 'http://sdmiramar.libguides.com/'
			)

		);

$arrPlanItems = array(
			0 => array
			(
				title => 'Program Review',
				url	=> '/campus/planning/framework/review'
			),
			1 => array
			(
				title => 'Alignment Taskforce',
				url	=> '/campus/planning/framework/alignment'
			),
			2 => array
			(
				title => 'Integrated Planning',
				url	=> '/campus/planning/framework'
			)
		);

  return [
    'lrccall'=> [
			'variables' =>
			[
				// define defaults for any variables you want in the twig file
				'items' =>  $arrLrcItems
			]
		],

    'plancall'=> [
			'variables' =>
			[
				// define defaults for any variables you want in the twig file
				'items' =>  $arrPlanItems
			]
		],
  ];
}

/*function miramarcustom_node_view(array &$build, NodeInterface $node, $display, $view_mode) {
  if ($node->getType() == 'home_page' && $view_mode == 'full') {
    //\Drupal::service('page_cache_kill_switch')->trigger();
  }
}*/


/*
function miramarcustom_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if ($view->id() == "get_started") {
	module_load_include('inc', 'views_jump_menu', 'views_jump_menu');
  }
}*/






